# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DrugduAppSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DrugduAppSwift
  pod 'SwiftTheme'
  pod 'Alamofire'
  pod 'HandyJSON', '~> 4.1.1'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
end
